name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Run Tests with Coverage
        run: flutter test --coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage/lcov.info
          fail_ci_if_error: false

      - name: PR Comment with Test Summary
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
